### ISSUE TITLE
Bump version?

### ISSUE THREAD

**Issue by jbreuer95** [infinitered/ignite-ir-boilerplate#110]
Hey guys,

Since #100 and #109 fixed some important problems can someone update the package here and on npm? I need to start a few new projects for my company and this would speed the project creation proces up alot :)

**Comment by jamonholmgren** [comment]
Hey @jbreuer95 ! We've bumped Ignite to 2.0.2 a couple days ago, although it looks like we haven't pushed any [release notes](https://github.com/infinitered/ignite-ir-boilerplate/releases) yet (cc @GantMan). We'll try to get those published.
