### ISSUE TITLE
LoginScreen.js file missing

### ISSUE THREAD

**Issue by ststaynov** [infinitered/ignite-ir-boilerplate#114]
> LoginScreen.js - an example login screen. Read the comments in there to learn more!

I guess this is not relative to the newest version of the Boilerplate since a LoginScreen.js file doesn't exist. Is it moved somewhere else or you just totally removed it?

**Comment by GantMan** [comment]
@derekgreenberg - can you elaborate and update this one.

**Comment by ststaynov** [comment]
@derekgreenberg will be very appreciated if you do!

**Comment by derekgreenberg** [comment]
@ststaynov The login screen example has been moved to this repo: https://github.com/infinitered/ignite-example-login . It's a WIP that awaits refactoring to improve and simplify the example code, plus a README that provides a walk-through of how the login screen works with react-nativation. But the login screen, reducer and saga can all be found in that repo.

**Comment by ststaynov** [comment]
Thanks for the reply! Cheers :)
