### ISSUE TITLE
react-router-navigation or react-native-navigation

### ISSUE THREAD

**Issue by Amurmurmur** [infinitered/ignite-ir-boilerplate#128]
First of all thank you so much for such a nice boilerplate setup!!!

Was wondering if there is an upcoming change in navigation ? 
Do you plan to maybe have another branch with different navigations and templates for rendering screen for each type of navigation?

**Comment by GantMan** [comment]
Hiya!

So right now our prescribed version is `react-navigation` but there's always the possibility of switching as one navigation system dominates the Mobile domain.  

I know react-router-navigation is very popular on web.  One thing I recommend, that if you're looking to switch navigation systems, is consider making a plugin that swaps the navigations out.  For now, and for simplicity we simply ship our preferred nav with he boilerplate.

https://github.com/infinitered/ignite/blob/master/docs/advanced-guides/creating-plugins.md

**Comment by Amurmurmur** [comment]
@GantMan 
Ok got it sweet, thank you so much for such a quick feedback!!
