### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by Amurmurmur** [infinitered/ignite-ir-boilerplate#134]
How to properly upgrade to 2.1.0 with all the changes currently setup project based on a previous version of this awesome boilerplate 2.0.1

I've setup a project via ignite cli

**Comment by jamonholmgren** [comment]
Hey @Amurmurmur , one way to do this is to generate a new boilerplate based on 2.1 and then copy over all the relevant files. Thanks for the kind words, by the way!
