### ISSUE TITLE
StoriesTest.js fails from missing dependency

### ISSUE THREAD

**Issue by ruddell** [infinitered/ignite-ir-boilerplate#139]
From a fresh minimal app, after #138, all tests pass except StoriesTest.js with:

    ignite new IgniteSampleApp --min
    npm run test
    ...
     FAIL  Tests/StoriesTest.js
      ● Test suite failed to run
    Cannot find module 'react-native-vector-icons/FontAwesome' from 'SearchBar.js'

Running `yarn add react-native-vector-icons` makes the generated tests pass, but I wasn't sure if you wanted to add a dependency or remove SearchBar because it's not used.  It is a nice example though.

I tried `ignite add vector-icons` but that has an issue of its own #137

**Comment by GantMan** [comment]
Great catch!  

@robinheinze @fvonhoven  and @carlinisaacson - Any interest in taking this simple issue?

**Comment by robinheinze** [comment]
I can take it. You want me to just remove the test?

**Comment by GantMan** [comment]
I'm thinking searchbar should be removed.

Thanks @robinheinze
