### ISSUE TITLE
Implement Devtools as a plugin

### ISSUE THREAD

**Issue by GantMan** [infinitered/ignite-ir-boilerplate#145]
Basically implement this PR in plugin form!

https://github.com/infinitered/ignite-ir-boilerplate/pull/144

**Comment by ryanlntn** [comment]
@GantMan Implemented as a plugin here: https://github.com/infinitered/ignite-redux-devtools
Published to npm here: https://www.npmjs.com/package/ignite-redux-devtools

**Comment by GantMan** [comment]
success!
