### ISSUE TITLE
Trying to use react-native 0.49.3 breaks

### ISSUE THREAD

**Issue by jacogreyling** [infinitered/ignite-ir-boilerplate#150]
I'm trying to create a new app with the latest stable release of react-native (v 0.49). Whilst the installation / set-up goes through fine, it fails horribly when I run 'react-native run-ios'. I know it's probably not officially supported by ignite but it will be useful. It also makes use of React 16.0.0 which has a number of improvements I would love to use. There also seem to be some peer dependency issues. When I however create a 'base' project using react-native-cli I don't get any of those errors which suggests issues with some of the libs used in ignite.

Set-up:

`ignite new IgniteSampleApp --react-native-version 0.49.3`

In the React Packager terminal I get the following error:

`ERROR  ENOENT: no such file or directory, lstat '/opt/Development/react-native/examples/IgniteSampleApp/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/React.build/Objects-normal/x86_64/RCTTouchEvent.o-70e60c84'`

Also doing a npm list, gives the following dependency warnings:

```
npm ERR! peer dep missing: react@0.13.x || 0.14.x || ^15.0.0-0 || 15.x, required by enzyme@2.9.1
npm ERR! peer dep missing: react@>=15.2.1 || 16.0.0-alpha.6 || 16.0.0-alpha.12, required by reactotron-react-native@1.12.3
npm ERR! peer dep missing: react-dom@^15.4.2, required by react-addons-test-utils@15.4.2
npm ERR! peer dep missing: @storybook/react@^3.2.12, required by @storybook/addon-storyshots@3.2.12
npm ERR! extraneous: node-pre-gyp@0.6.38 /opt/Development/react-native/examples/IgniteSampleApp/node_modules/node-pre-gyp
npm ERR! peer dep missing: react@react@^0.14.0 || ^15.0.0 || ^16.0.0, required by react-inspector@2.2.0
npm ERR! peer dep missing: react@^0.14.7 || ^15.0.0, required by @storybook/react-fuzzy@0.4.0
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0 || ^16.0.0, required by react-icons@2.2.7
npm ERR! peer dep missing: react@react@^0.14.0 || ^15.0.0 || ^16.0.0, required by react-inspector@2.2.0
npm ERR! peer dep missing: react@^0.14.7 || ^15.0.0, required by react-komposer@2.0.0
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0, required by react-modal@2.4.1
npm ERR! peer dep missing: react@^15.5.4, required by react-treebeard@2.0.3
npm ERR! peer dep missing: react-dom@^0.14.0 || ^15.0.0 || ^16.0.0, required by react-icons@2.2.7
npm ERR! peer dep missing: react-dom@^0.14.0 || ^15.0.0, required by react-modal@2.4.1
npm ERR! peer dep missing: react-dom@^15.5.4, required by react-treebeard@2.0.3
npm ERR! peer dep missing: react@^0.14.3 || ^15.0.0, required by react-komposer@1.13.1
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0, required by react-simple-di@1.2.0
npm ERR! peer dep missing: react@^0.14.7 || ^15.0.0, required by react-stubber@1.0.0
npm ERR! peer dep missing: react@^15.3.0 || ^16.0.0, required by radium@0.19.5
npm ERR! peer dep missing: react@^15.3.0 || ^16.0.0, required by velocity-react@1.3.3
npm ERR! peer dep missing: react-dom@^15.3.0 || ^16.0.0, required by velocity-react@1.3.3
npm ERR! peer dep missing: react@^15.0.0 || ^16.0.0, required by react-transition-group@1.2.1
npm ERR! peer dep missing: react-dom@^15.0.0 || ^16.0.0, required by react-transition-group@1.2.1
```

If anyone has solved these issues I would love to know more :)

Thx

**Comment by GantMan** [comment]
Looks like we have some fixes coming in on the next few days.  Look at the current PRs.

We'll be releasing soon as we're sure 0.49.3 is 💯

**Comment by jacogreyling** [comment]
Thank you @GantMan!

I've pulled the latest master and it now seems to work just fine. One thing though, there is still a lot of unresolved dependency issues.

`npm ERR! peer dep missing: react@0.13.x || 0.14.x || ^15.0.0-0 || 15.x, required by enzyme@2.9.1
npm ERR! peer dep missing: react@>=15.2.1 || 16.0.0-alpha.6 || 16.0.0-alpha.12, required by reactotron-react-native@1.12.3
npm ERR! peer dep missing: react-dom@^15.4.2, required by react-addons-test-utils@15.4.2
npm ERR! peer dep missing: @storybook/react@^3.2.12, required by @storybook/addon-storyshots@3.2.12
npm ERR! invalid: ignite-ir-boilerplate@2.1.1 /opt/Development/react-native/examples/IgniteIrBoilerplate/node_modules/ignite-ir-boilerplate
npm ERR! extraneous: babel-eslint@7.2.3 /opt/Development/react-native/examples/IgniteIrBoilerplate/node_modules/ignite-ir-boilerplate/node_modules/babel-eslint
npm ERR! extraneous: fs-jetpack@1.2.0 /opt/Development/react-native/examples/IgniteIrBoilerplate/node_modules/ignite-ir-boilerplate/node_modules/fs-jetpack
npm ERR! extraneous: jest@20.0.4 /opt/Development/react-native/examples/IgniteIrBoilerplate/node_modules/ignite-ir-boilerplate/node_modules/jest
npm ERR! extraneous: np@2.16.0 /opt/Development/react-native/examples/IgniteIrBoilerplate/node_modules/ignite-ir-boilerplate/node_modules/np
npm ERR! extraneous: sinon@2.4.1 /opt/Development/react-native/examples/IgniteIrBoilerplate/node_modules/ignite-ir-boilerplate/node_modules/sinon
npm ERR! extraneous: standard@10.0.3 /opt/Development/react-native/examples/IgniteIrBoilerplate/node_modules/ignite-ir-boilerplate/node_modules/standard
npm ERR! extraneous: tempy@0.1.0 /opt/Development/react-native/examples/IgniteIrBoilerplate/node_modules/ignite-ir-boilerplate/node_modules/tempy
npm ERR! extraneous: ramda@0.23.0 /opt/Development/react-native/examples/IgniteIrBoilerplate/node_modules/ignite-ir-boilerplate/node_modules/ramda
npm ERR! extraneous: node-pre-gyp@0.6.38 /opt/Development/react-native/examples/IgniteIrBoilerplate/node_modules/node-pre-gyp
npm ERR! peer dep missing: react@react@^0.14.0 || ^15.0.0 || ^16.0.0, required by react-inspector@2.2.0
npm ERR! peer dep missing: react@^0.14.7 || ^15.0.0, required by @storybook/react-fuzzy@0.4.0
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0 || ^16.0.0, required by react-icons@2.2.7
npm ERR! peer dep missing: react@react@^0.14.0 || ^15.0.0 || ^16.0.0, required by react-inspector@2.2.0
npm ERR! peer dep missing: react@^0.14.7 || ^15.0.0, required by react-komposer@2.0.0
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0, required by react-modal@2.4.1
npm ERR! peer dep missing: react@^15.5.4, required by react-treebeard@2.0.3
npm ERR! peer dep missing: react-dom@^0.14.0 || ^15.0.0 || ^16.0.0, required by react-icons@2.2.7
npm ERR! peer dep missing: react-dom@^0.14.0 || ^15.0.0, required by react-modal@2.4.1
npm ERR! peer dep missing: react-dom@^15.5.4, required by react-treebeard@2.0.3
npm ERR! peer dep missing: react@^0.14.3 || ^15.0.0, required by react-komposer@1.13.1
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0, required by react-simple-di@1.2.0
npm ERR! peer dep missing: react@^0.14.7 || ^15.0.0, required by react-stubber@1.0.0
npm ERR! peer dep missing: react@^15.3.0 || ^16.0.0, required by radium@0.19.5
npm ERR! peer dep missing: react@^15.3.0 || ^16.0.0, required by velocity-react@1.3.3
npm ERR! peer dep missing: react-dom@^15.3.0 || ^16.0.0, required by velocity-react@1.3.3
npm ERR! peer dep missing: react@^15.0.0 || ^16.0.0, required by react-transition-group@1.2.1
npm ERR! peer dep missing: react-dom@^15.0.0 || ^16.0.0, required by react-transition-group@1.2.1`

This doesn't seem to break anything but just an FYI. Also probably best to upgrade to React 16.0.0 GA?

Just my two cents :)

**Comment by guhungry** [comment]
Need to upgrade enzyme to version 3 to suppkrt react 16 and need to install react 16 adapter (have to config in test setup file)

**Comment by skellock** [comment]
I agree with @jacogreyling.

In `react-native@0.49.3`, they use `react@16.0.0-beta.5` which is API compatible with `react@16`.  I've tested this on another project.

And although I haven't used enzyme in a while, @guhungry, but that totally makes sense to me.
