### ISSUE TITLE
Upgrade to latest packages

### ISSUE THREAD

**Issue by nonameolsson** [infinitered/ignite-ir-boilerplate#159]
A lot of packages are out of date. 

- Upgrade to latest versions of all packages
- Make required changes to boilerplate so it works with the latest packages.

I will try to make a PR for this. But someone else is of course welcome to do it also :)

**Comment by jamonholmgren** [comment]
Good call @nonameolsson, sounds like a plan.

**Comment by GantMan** [comment]
For redux persist fix here:  https://github.com/infinitered/ignite-redux-persist/blob/master/plugin.js
