### ISSUE TITLE
jest "testMatch" not working properly

### ISSUE THREAD

**Issue by mcxsic** [infinitered/ignite-ir-boilerplate#169]
Hi!
I came across an issue and I think that is related to the boilerplate. I'm using [Ignite](https://github.com/infinitered/ignite) to crate my React Native app, and I'm using this boilerplate. Right now, and once the boilerplate is created, if I run `npm test` or `npm run test`, it calls jest, but it starts reading all the JS files, not only the tests that are in the `<root>/Tests` folder. Since the files outside the `Tests` folder are not actual tests, there's a lot of errors. I realized that if I modify the following lines from the `package.json`...:
```
"jest": {
    "preset": "react-native",
    "testMatch": ["***/Tests/**/*.js?(x)", "**/?(*.)(spec|test).js?(x)"],
    "testPathIgnorePatterns": ["/node_modules/", "Tests/Setup.js"],
    "setupFiles": ["./Tests/Setup"]
  },
```
...to...
```
"jest": {
    "preset": "react-native",
    "testMatch": ["<rootDir>/Tests/**/*.js?(x)", "**/?(*.)(spec|test).js?(x)"],
    "testPathIgnorePatterns": ["/node_modules/", "<rootDir>/Tests/Setup.js"],
    "setupFiles": ["<rootDir>/Tests/Setup"]
  },
```

it works as expected, only reading the tests inside `Tests` and passing all the tests.
Is that an actual error on the configuration of the package.json? or am I doing something wrong? 

Thanks,

**Comment by jamonholmgren** [comment]
Hey @mcxsic , thanks for using Ignite! I spun up a new boilerplate and all my tests pass. 🤔 

Are you running `npm test` in your root folder?

**Comment by jamonholmgren** [comment]
Also, what is the result of `ignite doctor` ?

**Comment by mcxsic** [comment]
hi @jamonholmgren! Yes, I'm running it in the root folder of the project. This is my information:
```
System
  platform           darwin
  arch               x64
  cpu                8 cores                                                                    Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  directory          /Users/mcxsic/Documents/Tests/react-native-boilerplate/RNIgniteTest

JavaScript
  node               8.5.0        /Users/mcxsic/.nvm/versions/node/v8.5.0/bin/node
  npm                5.5.1        /Users/mcxsic/.nvm/versions/node/v8.5.0/bin/npm
  yarn               1.2.1        /Users/mcxsic/.nvm/versions/node/v8.5.0/bin/yarn

React Native
  react-native-cli   2.0.1
  app rn version     0.49.3

Ignite
  ignite             2.0.0        /Users/mcxsic/.nvm/versions/node/v8.5.0/bin/ignite

Android
  java               1.8.0_101    /usr/bin/java
  android home       -            /Users/mcxsic/Library/Android/sdk

iOS
  xcode              9.1
```

**Comment by jamonholmgren** [comment]
Does it happen if you upgrade to node 8.9.1 and/or yarn 1.3.2?

**Comment by mcxsic** [comment]
I updated node to 9.2.0  (yarn was already 1.3.2), I created a fresh boilerplate with `ignite new igniteTest` but `npm test` is still not working :(

**Comment by jamonholmgren** [comment]
Hm, I'm having trouble recreating.

![image](https://user-images.githubusercontent.com/1479215/33055414-61cc7264-ce34-11e7-9b70-04d174951990.png)

@GantMan @skellock Any ideas?

**Comment by jamonholmgren** [comment]
What options are you selecting when you do `ignite new` ?

**Comment by mcxsic** [comment]
I tried selecting all of them (`react-native-vector-icons`,  `react-native-i18n` and `react-native-animatable`) and none of them, using `ignite-ir-boilerplate`, and I had the same result.

**Comment by mcxsic** [comment]
Ok I figured out what was the issue! it turns out that I always put my code tests inside the `~/Documents/Tests` folder and with the current "testMatch" is matching that folder. That means that if I do:

```
~/Documents/Tests/AwesomeProject $ npm test
```
it doesn't work but if the folder is outside the `Tests` folder:

```
~/Documents/AwesomeProject $ npm test
```
Then it works. As far as I understand the the boilerplate should only look for tests inside the folder where we are working on, so I guess that my initial solution:

```
"jest": {
    "preset": "react-native",
    "testMatch": ["<rootDir>/Tests/**/*.js?(x)", "**/?(*.)(spec|test).js?(x)"],
    "testPathIgnorePatterns": ["/node_modules/", "<rootDir>/Tests/Setup.js"],
    "setupFiles": ["<rootDir>/Tests/Setup"]
  },
```
should be the right one. What do you think?

**Comment by jamonholmgren** [comment]
Interesting! As long as it continues to work with "Normal" setups I don't mind that change. PR? :)

**Comment by mcxsic** [comment]
yep! :)

**Comment by mcxsic** [comment]
pull request here: #171
