### ISSUE TITLE
TypeError: addListener is not a function

### ISSUE THREAD

**Issue by 2f-concept** [infinitered/ignite-ir-boilerplate#184]
Hi and thanks for this project !

I got this error just after creating a new project with command : 
ignit new projectname --max
cd projectname
react-native run-android

transpile goes well but after application start i got this :

TypeError: addListener is not a function

This error is located at:
    in CardStack (at CardStackTransitioner.js:66)
    in RCTView (at View.js:113)
    in View (at Transitioner.js:151)
    in Transitioner (at CardStackTransitioner.js:19)
    in CardStackTransitioner (at StackNavigator.js:38)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:205)
    in NavigationContainer (at ReduxNavigation.js:14)
    in ReduxNavigation (created by Connect(ReduxNavigation))
    in Connect(ReduxNavigation) (at RootContainer.js:19)
    in RCTView (at View.js:113)
    in View (at RootContainer.js:17)
    in RootContainer (created by Connect(RootContainer))
    in Connect(RootContainer) (at App.js:24)
    in Provider (at App.js:23)
    in App
    in RCTView (at View.js:113)
    in View
    in Unknown (at renderApplication.js:35)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:113)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)

please help

**Comment by Amurmurmur** [comment]
@2f-concept This error happens due to react-navigation 1.0.28+ changed the api slightly.
I've made https://github.com/infinitered/ignite-ir-boilerplate/pull/185 to support the change.

Hopefully guys from infinitered will approve as soon as they can get their hands on it. 👍

**Comment by silasjmatson** [comment]
This should be resolved in #185
