### ISSUE TITLE
TypeError : undefined is not a function (evaluating 'addListener') thanks for the help

### ISSUE THREAD

**Issue by ibrahim-lahribli** [infinitered/ignite-ir-boilerplate#201]
Hi guys i just start working with this boilerplate so i had lunched the ignite new MyLatestCreation command after that when im trying to run the application on android emulator, i'm getting this error on the screen of the emulator.

![capture](https://user-images.githubusercontent.com/19494141/38731846-e4c3c730-3f13-11e8-8292-211f1ff35b82.PNG)

please some help here guys,im just start working with react native

**Comment by tristola** [comment]
I had the same issue when generating the boilerplate without the development screens, try to create one with them, it should work.

**Comment by ibrahim-lahribli** [comment]
@tristola  Thanks lot man for your response.
yes you are right, i made this changes and it works you save me a lot of time thanks.
