### ISSUE TITLE
Next version of React Native

### ISSUE THREAD

**Issue by jamonholmgren** [infinitered/ignite-ir-boilerplate#35]
This issue replaces https://github.com/infinitered/ignite/issues/957 for tracking React Native version bump from 0.42+.

React Native 0.43 and 0.44 use `React 16.0.0-alpha` which isn't very friendly with React Native. @skellock recommends we wait for 0.45 before updating `ignite-ir-next`.

**Comment by skellock** [comment]
I have 0.44 up & running on my active project here.  I think as long as we're not using `enzyme` and `react-native-router-flux` and are ok with a few warnings showing up (like `reactotron-react-native` - i know, i know), then `0.44.x` is fine to upgrade.

**Comment by skellock** [comment]
I'll add `react-native-maps` into that mix too.  they just refactored their codebase, and it might no longer be compatible.  We'll have to revisit that as well.

**Comment by skellock** [comment]
Make the pain stop @jamonholmgren .

**Comment by skellock** [comment]
Now that we're off `react-native-router-flux`, we good to upgrade.

There is a minor issue with warnings appearing (Facebook's issue), but running `yarn` a final time or `npm dedupe` makes the warnings go away (they are with the library `bser`).

I say, let's hold off for a week, then go to `0.45.0`.

(BTW:  If anyone wants to use 0.44.2, you can run `ignite new Latest --react-native-version 0.44.2` in the meantime).

**Comment by skellock** [comment]
We're now using `0.42.3` as of `2.0.0-rc.6`.
