### ISSUE TITLE
Wrong navigation plugin ?

### ISSUE THREAD

**Issue by qwert666** [infinitered/ignite-ir-boilerplate#65]
It seems as the project depends on react-navigation and not on react-native-router-flux

[CustomNavBar](https://github.com/infinitered/ignite-ir-boilerplate/blob/master/boilerplate/App/Components/CustomNavBar.js#L6)

**Comment by skellock** [comment]
Seems  like we missed that, thx for the heads up.

**Comment by GantMan** [comment]
I'm surprised the e2e tests didn't squawk and fail.   Easy enough to fix, but we should really take the time to add a test that would have caught this.

**Comment by skellock** [comment]
#68 has a fix for this in place.
