### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect error

### ISSUE THREAD

**Issue by crcury14** [infinitered/ignite-ir-boilerplate#76]
I get this error after adding the boilerplate when creating a new ignite app:

The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.
The filename, directory name, or volume label syntax is incorrect.
an error occured while installing ignite-ir-boilerplate boilerplate.
Error: not found: git

**Comment by skellock** [comment]
https://github.com/infinitered/ignite/issues/1081 Let’s track over here.
