### ISSUE TITLE
Redux-persist with combined reducers

### ISSUE THREAD

**Issue by vincejah** [infinitered/ignite-ir-boilerplate#77]
My root reducer looks like this:

```
  const rootReducer = combineReducers({
    app: require('./AppRedux').reducer,
    auth: require('./AuthRedux').reducer,
    services: combineReducers({
      reducer1: require('./Key1Redux').reducer,
      reducer2: require('./Key2Redux').reducer
    }),
```

if I add `services`into the whitelist of persist-redux, i get the following error:

`console.error: "Unexpected key "mergeDeep" found in previous state received by the reducer. Expected to find one of the known reducer keys instead: "reducer1", "reducer2". Unexpected keys will be ignored."`

What is the correct way to make `services`persistent?

**Comment by skellock** [comment]
Our transform for redux config needs to be brought up to date.  [This is](https://github.com/infinitered/ignite-ir-boilerplate/blob/master/boilerplate/App/Services/ImmutablePersistenceTransform.js#L29) from the ReduxPersist 2 days.

**Comment by GantMan** [comment]
@skellock - Do you think we should be using https://github.com/rt2zz/redux-persist-immutable ???

@vincejah - can you give this a go and let us know if it works?   https://github.com/rt2zz/redux-persist-transform-immutable

**Comment by skellock** [comment]
That one is for Immutable.js I think.  But ya, we’d need the seamless-immutable version of that.

**Comment by jbreuer95** [comment]
i get this without an second combineReducers too

**Comment by heyjared** [comment]
This seems related to [this issue](https://github.com/infinitered/ignite/issues/271) and it appears [this line](https://github.com/infinitered/ignite-ir-boilerplate/blob/7a08b490fb49e745401ed75bc2f5ac251f098bdf/boilerplate/App/Services/ImmutablePersistenceTransform.js#L29) that is causing it. However, as @skellock speculated, this seems to not be necessary anymore as of [this merge request](https://github.com/rt2zz/redux-persist/pull/216/files). Commenting out the L29 in ImmutablePersistenceTransform seems to resolve the issue.

**Comment by skellock** [comment]
Thx @heyjared !

**Comment by dhanala89** [comment]
How do i persist specific properties of the reducer? For example I have a login reducer which has properties such as username, password, employee_number. In this case I want to persist just the employee_number and not the username and password. Is this possible? If yes then can you please post an example?

**Comment by GantMan** [comment]
If you only want to persist certain parts I suggest 2 methods.

1 - Move just those parts to a separate reducer that is rehydrated.
2 - Store them yourself with [Async storage](https://facebook.github.io/react-native/docs/asyncstorage.html)
^ plenty of examples of that in the docs, and it comes free with RN

**Comment by salhotra** [comment]
@GantMan Redux persist gives the ability to blacklist nested state properties.
`https://github.com/rt2zz/redux-persist#nested-persists`
When this is implemented, it breaks the app
