### ISSUE TITLE
Listview sections generator naming

### ISSUE THREAD

**Issue by tmaly1980** [infinitered/ignite-ir-boilerplate#90]
The generator for the ListView sectioned screen doesn't rename the class to what we provide it, it's still ListviewSectionsExample in the file, even though the filename is what it should be (user provided). If I generate a Listview that does NOT use sections, those boilerplate containers are class named properly.

**Comment by jamonholmgren** [comment]
@tmaly1980 Would you be willing to take a crack at this one?
