### ISSUE TITLE
AIDL is missing

### ISSUE THREAD

**Issue by HelloEdit** [infinitered/ignite-ir-boilerplate#95]
Hello !

Today, I start new project with ignite and vector-icons as dependency.
But when I launch `yarn android:build` in bash, I get this:
```
[...]
:react-native-vector-icons:compileReleaseAidl FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-vector-icons:compileReleaseAidl'.
> java.lang.IllegalStateException: aidl is missing
```
So, I try on windows CLI
```
[...]
:app:generateReleaseResources
:app:mergeReleaseResources
:app:bundleReleaseJsAndAssets

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task 'bundleReleaseJsAndAssets' during up-to-date check.
> java.io.FileNotFoundException: C:\Users\NSA\Documents\Lab\BigBrowser\node_modules\.bin\format-json (can't open / access file)
```
I don't know if I should open issue on react-native repo...
So for the moment ... I can't build my project... PLEASE HELP ME !

---

I use the latest ignite CLI with RN 0.45.1 for features reasons

**Comment by jbreuer95** [comment]
The boilerplate has been updated to a version which has 0.45.1 as default version, might want to try that one?

**Comment by HelloEdit** [comment]
Hum... Are you sure ? Because ignite start a new project with React Native 0.42.0... I will check after 😉

**Comment by jbreuer95** [comment]
Yeah i did a `ingnite new` yesterday and got version 0.45.1 :). Might also wanna update `ingnite-cli` but i dont think that makes a diffrence

**Comment by HelloEdit** [comment]
My bad, I will try on a new project ! But today I try a project with RN 0.46.0-rc.3, and AIDL is still missing... I think only vector-icons team can be solve this problem...
I feel a little useless 😄

**Comment by HelloEdit** [comment]
Ok bash subsystem and CMD says "nop":
bash:
```
[...]
:react-native-vector-icons:prepareReleaseDependencies
:react-native-vector-icons:compileReleaseAidl FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-vector-icons:compileReleaseAidl'.
> java.lang.IllegalStateException: aidl is missing
```
CMD:
```
[...]
:app:mergeReleaseResources UP-TO-DATE
:app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Failed to capture snapshot of input files for task 'bundleReleaseJsAndAssets' property '$1' during up-to-date check.
> Failed to create MD5 hash for file 'C:\Users\coren\Documents\Lab\test\node_modules\.bin\format-json'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by HelloEdit** [comment]
facebook/react-native#14733
