### ISSUE TITLE
Outdated on NPM

### ISSUE THREAD

**Issue by jbreuer95** [infinitered/ignite-ir-boilerplate#96]
Could you guys update NPM to the rc.7 version so ignite new will use this latest awesome one :)

**Comment by skellock** [comment]
Oops, it looks like it was deployed to the `next` dist-tag by mistake.

**Comment by skellock** [comment]
Good to go.  Thx for the heads up.

**Comment by jamonholmgren** [comment]
This is strange...I thought I ran the command to update it to `latest` after deploying. `np` doesn't let me tag with `latest` unfortunately, so it's a separate step.

**Comment by skellock** [comment]
Ya no worries dude. Once we go back to regular version numbers, it won’t be a problem. You can also follow it up with a quick `npm publish`.
